Repository KU-rum/backend, pull requests merged in 2024-11, with the labels that each got.

#17 feat: 건물 핀포인트 확인 api 구현
  .idea/modules.xml
  .idea/modules/backend.main.iml
  backend/src/main/java/ku_rum/backend/domain/building/controller/BuildingSearchController.java
  backend/src/main/java/ku_rum/backend/domain/building/domain/Building.java
  backend/src/main/java/ku_rum/backend/domain/building/dto/response/BuildingResponse.java
  backend/src/main/java/ku_rum/backend/domain/building/repository/BuildingClassRepository.java
  backend/src/main/java/ku_rum/backend/domain/building/repository/BuildingRepository.java
  backend/src/main/java/ku_rum/backend/domain/building/service/BuildingAbbrev.java
  backend/src/main/java/ku_rum/backend/domain/building/service/BuildingSearchService.java
  backend/src/main/java/ku_rum/backend/global/config/QueryDslConfig.java
  backend/src/main/java/ku_rum/backend/global/exception/building/BuildingNotFoundException.java
  backend/src/main/java/ku_rum/backend/global/exception/building/BuildingNotRegisteredException.java
  backend/src/main/java/ku_rum/backend/global/handler/ControllerAdvice.java
  backend/src/main/java/ku_rum/backend/global/response/status/BaseExceptionResponseStatus.java
  backend/src/test/java/ku_rum/backend/common/BaseControllerTest.java
  backend/src/test/java/ku_rum/backend/domain/building/controller/BuildingSearchControllerTest.java
  backend/src/test/java/ku_rum/backend/domain/building/service/BuildingSearchServiceTest.java
  backend/src/test/java/ku_rum/backend/domain/user/application/UserServiceTest.java
Labels: enhancement, BE

#22 feat: 공지사항 크롤링 API 구현
  backend/build.gradle
  backend/src/main/java/ku_rum/backend/domain/notice/application/NoticeService.java
  backend/src/main/java/ku_rum/backend/domain/notice/domain/Notice.java
  backend/src/main/java/ku_rum/backend/domain/notice/domain/NoticeCategory.java
  backend/src/main/java/ku_rum/backend/domain/notice/domain/NoticeStatus.java
  backend/src/main/java/ku_rum/backend/domain/notice/domain/repository/NoticeRepository.java
  backend/src/main/java/ku_rum/backend/domain/notice/dto/response/NoticeSimpleResponse.java
  backend/src/main/java/ku_rum/backend/domain/notice/presentation/NoticeController.java
  backend/src/test/java/ku_rum/backend/domain/bookmark/domain/BookmarkTest.java
  backend/src/test/java/ku_rum/backend/domain/notice/application/NoticeServiceTest.java
  backend/src/test/java/ku_rum/backend/domain/notice/domain/NoticeTest.java
  backend/src/test/java/ku_rum/backend/domain/notice/presentation/NoticeControllerTest.java
Labels: Feature, BE

#20 feat: 위인전 로그인 API 구현
  .idea/gradle.xml
  backend/build.gradle
  backend/src/main/java/ku_rum/backend/domain/user/application/UserService.java
  backend/src/main/java/ku_rum/backend/domain/user/dto/request/WeinLoginRequest.java
  backend/src/main/java/ku_rum/backend/domain/user/dto/response/WeinLoginResponse.java
  backend/src/main/java/ku_rum/backend/domain/user/presentation/UserController.java
  backend/src/main/java/ku_rum/backend/global/response/BaseResponse.java
  backend/src/test/java/ku_rum/backend/domain/user/presentation/UserControllerTest.java
Labels: Feature, BE

#24 feat: 스프링 시큐리티 적용
  backend/build.gradle
  backend/src/main/java/ku_rum/backend/domain/user/application/UserService.java
  backend/src/main/java/ku_rum/backend/global/config/SecurityConfig.java
  backend/src/test/java/ku_rum/backend/domain/user/application/UserServiceTest.java
  backend/src/test/java/ku_rum/backend/domain/user/presentation/MailControllerTest.java
  backend/src/test/java/ku_rum/backend/domain/user/presentation/UserControllerTest.java
Labels: environment, BE
