Repository KU-rum/backend, pull requests merged in 2025-01, with the labels that each got.

#26 feat: 카테고리로 전체,디테일 조회
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/modules/backend.main.iml
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/ku_rum/backend/BackendApplication.java
  backend/src/main/java/ku_rum/backend/domain/building/application/BuildingSearchService.java
  backend/src/main/java/ku_rum/backend/domain/building/controller/BuildingSearchController.java
  backend/src/main/java/ku_rum/backend/domain/building/domain/Building.java
  backend/src/main/java/ku_rum/backend/domain/building/domain/BuildingAbbrev.java
  backend/src/main/java/ku_rum/backend/domain/building/domain/repository/BuildingCategoryQueryRepository.java
  backend/src/main/java/ku_rum/backend/domain/building/domain/repository/BuildingCategoryRepository.java
  backend/src/main/java/ku_rum/backend/domain/building/domain/repository/BuildingClassRepository.java
  backend/src/main/java/ku_rum/backend/domain/building/domain/repository/BuildingInitializer.java
  backend/src/main/java/ku_rum/backend/domain/building/domain/repository/BuildingQueryRepository.java
  backend/src/main/java/ku_rum/backend/domain/building/domain/repository/BuildingRepository.java
  backend/src/main/java/ku_rum/backend/domain/building/dto/response/BuildingResponse.java
  backend/src/main/java/ku_rum/backend/domain/building/presentation/BuildingSearchController.java
  backend/src/main/java/ku_rum/backend/domain/building/service/BuildingSearchService.java
  backend/src/main/java/ku_rum/backend/domain/category/application/CategoryService.java
  backend/src/main/java/ku_rum/backend/domain/category/domain/CategoryDetail.java
  backend/src/main/java/ku_rum/backend/domain/category/domain/CategoryType.java
  backend/src/main/java/ku_rum/backend/domain/category/domain/repository/CategoryQueryRepository.java
  backend/src/main/java/ku_rum/backend/domain/category/domain/repository/CategoryRepository.java
  backend/src/main/java/ku_rum/backend/domain/category/dto/response/CategoryDetailFloorAndMenusProviding.java
  backend/src/main/java/ku_rum/backend/domain/category/dto/response/CategoryDetailResponse.java
  backend/src/main/java/ku_rum/backend/domain/category/dto/response/CategoryKcubeDetailResponse.java
  backend/src/main/java/ku_rum/backend/domain/menu/repository/MenuQueryRepository.java
  backend/src/main/java/ku_rum/backend/domain/menu/response/MenuSimpleResponse.java
  backend/src/main/java/ku_rum/backend/domain/user/application/UserService.java
  backend/src/main/java/ku_rum/backend/global/exception/building/BuildingNotRegisteredException.java
  backend/src/main/java/ku_rum/backend/global/exception/category/CategoryNotExist.java
  backend/src/main/java/ku_rum/backend/global/exception/category/CategoryNotProvidingDetail.java
  backend/src/main/java/ku_rum/backend/global/handler/ControllerAdvice.java
  backend/src/main/java/ku_rum/backend/global/response/BaseResponse.java
  backend/src/main/java/ku_rum/backend/global/response/status/BaseExceptionResponseStatus.java
  backend/src/test/java/ku_rum/backend/domain/bookmark/domain/BookmarkTest.java
  backend/src/test/java/ku_rum/backend/domain/building/controller/BuildingSearchControllerTest.java
  backend/src/test/java/ku_rum/backend/domain/building/domain/BuildingCategoryTest.java
  backend/src/test/java/ku_rum/backend/domain/building/domain/BuildingTest.java
  backend/src/test/java/ku_rum/backend/domain/building/service/BuildingCategoryInfoServiceTest.java
  backend/src/test/java/ku_rum/backend/domain/building/service/BuildingInfoServiceTest.java
  backend/src/test/java/ku_rum/backend/domain/building/service/BuildingSearchServiceTest.java
  backend/src/test/java/ku_rum/backend/domain/department/domain/DepartmentTest.java
  backend/src/test/java/ku_rum/backend/domain/friend/application/FriendServiceTest.java
  backend/src/test/java/ku_rum/backend/domain/friend/domain/FriendTest.java
  backend/src/test/java/ku_rum/backend/domain/notice/domain/NoticeTest.java
  backend/src/test/java/ku_rum/backend/domain/user/application/UserServiceTest.java
  backend/src/test/java/ku_rum/backend/domain/user/domain/UserTest.java
  backend/src/test/java/ku_rum/backend/domain/user/domain/repository/UserRepositoryTest.java
Labels: BE, D-2

#37 GPT api 연결 및 크롤링 코드 리펙토링
  .idea/gradle.xml
  backend/build.gradle
  backend/src/main/java/ku_rum/backend/domain/openai/config/OpenAiConfig.java
  backend/src/main/java/ku_rum/backend/domain/openai/dto/GPTRequest.java
  backend/src/main/java/ku_rum/backend/domain/openai/dto/GPTResponse.java
  backend/src/main/java/ku_rum/backend/domain/openai/dto/Message.java
  backend/src/main/java/ku_rum/backend/domain/openai/presentation/ChatBotController.java
  backend/src/main/java/ku_rum/backend/domain/reservation/application/ReservationService.java
  backend/src/main/java/ku_rum/backend/domain/reservation/domain/ReservationCategory.java
  backend/src/main/java/ku_rum/backend/domain/reservation/dto/RoomReservation.java
  backend/src/main/java/ku_rum/backend/domain/reservation/dto/TimeTable.java
  backend/src/main/java/ku_rum/backend/domain/reservation/dto/request/SelectDateRequest.java
  backend/src/main/java/ku_rum/backend/domain/reservation/dto/request/WeinLoginRequest.java
  backend/src/main/java/ku_rum/backend/domain/reservation/dto/response/WeinLoginResponse.java
  backend/src/main/java/ku_rum/backend/domain/reservation/presentation/ReservationController.java
  backend/src/main/java/ku_rum/backend/domain/user/application/UserService.java
  backend/src/main/java/ku_rum/backend/domain/user/domain/repository/ReservationRepository.java
  backend/src/main/java/ku_rum/backend/domain/user/dto/request/WeinLoginRequest.java
  backend/src/main/java/ku_rum/backend/domain/user/presentation/UserController.java
  backend/src/main/java/ku_rum/backend/global/response/BaseResponse.java
  backend/src/main/resources/application.yml
  backend/src/test/java/ku_rum/backend/domain/reservation/application/ReservationServiceTest.java
  backend/src/test/java/ku_rum/backend/domain/reservation/presentation/ReservationControllerTest.java
  backend/src/test/java/ku_rum/backend/domain/user/presentation/UserControllerTest.java
Labels: Refactor, Feature, BE, D-2

#41 Feat: 인증/인가를 위한 AccessToken, RefreshToken 적용
  .idea/.gitignore
  .idea/7.38.iml
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/backend.main.iml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  backend/build.gradle
  backend/docker-compose.yml
  backend/src/main/java/ku_rum/backend/domain/friend/application/FriendService.java
  backend/src/main/java/ku_rum/backend/domain/user/application/AuthService.java
  backend/src/main/java/ku_rum/backend/domain/user/application/UserService.java
  backend/src/main/java/ku_rum/backend/domain/user/domain/User.java
  backend/src/main/java/ku_rum/backend/domain/user/domain/repository/ReservationRepository.java
  backend/src/main/java/ku_rum/backend/domain/user/domain/repository/UserRepository.java
  backend/src/main/java/ku_rum/backend/domain/user/dto/request/AuthRequest.java
  backend/src/main/java/ku_rum/backend/domain/user/dto/request/ReissueRequest.java
  backend/src/main/java/ku_rum/backend/domain/user/dto/request/WeinLoginRequest.java
  backend/src/main/java/ku_rum/backend/domain/user/dto/response/WeinLoginResponse.java
  backend/src/main/java/ku_rum/backend/domain/user/presentation/AuthController.java
  backend/src/main/java/ku_rum/backend/domain/user/presentation/UserController.java
  backend/src/main/java/ku_rum/backend/global/config/RedisConfig.java
  backend/src/main/java/ku_rum/backend/global/config/RedisTestController.java
  backend/src/main/java/ku_rum/backend/global/config/RedisUtil.java
  backend/src/main/java/ku_rum/backend/global/config/SecurityConfig.java
  backend/src/main/java/ku_rum/backend/global/handler/ControllerAdvice.java
  backend/src/main/java/ku_rum/backend/global/response/BaseResponse.java
  backend/src/main/java/ku_rum/backend/global/response/status/BaseExceptionResponseStatus.java
  backend/src/main/java/ku_rum/backend/global/security/jwt/CustomUserDetails.java
  backend/src/main/java/ku_rum/backend/global/security/jwt/JwtProperties.java
  backend/src/main/java/ku_rum/backend/global/security/jwt/JwtTokenAuthenticationFilter.java
  backend/src/main/java/ku_rum/backend/global/security/jwt/JwtTokenProvider.java
  backend/src/main/java/ku_rum/backend/global/security/jwt/TokenResponse.java
  backend/src/test/java/ku_rum/backend/domain/user/domain/repository/UserRepositoryTest.java
Labels: Feature, D-3

#44 refactor: 전반적인 코드 리팩토링 및 RestDocs 적용
  backend/build.gradle
  backend/docker-compose.yml
  backend/src/docs/asciidoc/user.adoc
  backend/src/main/java/ku_rum/backend/domain/friend/application/FriendService.java
  backend/src/main/java/ku_rum/backend/domain/friend/dto/request/FriendFindRequest.java
  backend/src/main/java/ku_rum/backend/domain/friend/dto/request/FriendListRequest.java
  backend/src/main/java/ku_rum/backend/domain/friend/dto/response/FriendFindResponse.java
  backend/src/main/java/ku_rum/backend/domain/friend/dto/response/FriendListResponse.java
  backend/src/main/java/ku_rum/backend/domain/user/application/UserService.java
  backend/src/main/java/ku_rum/backend/domain/user/application/auth/AuthService.java
  backend/src/main/java/ku_rum/backend/domain/user/application/mail/MailService.java
  backend/src/main/java/ku_rum/backend/domain/user/dto/request/AuthRequest.java
  backend/src/main/java/ku_rum/backend/domain/user/dto/request/EmailValidationRequest.java
  backend/src/main/java/ku_rum/backend/domain/user/dto/request/MailSendRequest.java
  backend/src/main/java/ku_rum/backend/domain/user/dto/request/MailVerificationRequest.java
  backend/src/main/java/ku_rum/backend/domain/user/dto/request/UserSaveRequest.java
  backend/src/main/java/ku_rum/backend/domain/user/dto/request/auth/LoginRequest.java
  backend/src/main/java/ku_rum/backend/domain/user/dto/request/auth/ReissueRequest.java
  backend/src/main/java/ku_rum/backend/domain/user/dto/request/mail/EmailValidationRequest.java
  backend/src/main/java/ku_rum/backend/domain/user/dto/request/mail/MailSendRequest.java
  backend/src/main/java/ku_rum/backend/domain/user/dto/request/mail/MailVerificationRequest.java
  backend/src/main/java/ku_rum/backend/domain/user/dto/response/UserSaveResponse.java
  backend/src/main/java/ku_rum/backend/domain/user/dto/response/mail/MailVerificationResponse.java
  backend/src/main/java/ku_rum/backend/domain/user/presentation/AuthController.java
  backend/src/main/java/ku_rum/backend/domain/user/presentation/UserController.java
  backend/src/main/java/ku_rum/backend/domain/user/presentation/auth/AuthController.java
  backend/src/main/java/ku_rum/backend/domain/user/presentation/mail/MailController.java
  backend/src/main/java/ku_rum/backend/global/config/redis/RedisCacheConfig.java
  backend/src/main/java/ku_rum/backend/global/config/redis/RedisConfig.java
  backend/src/main/java/ku_rum/backend/global/config/redis/RedisUtil.java
  backend/src/main/java/ku_rum/backend/global/config/security/SecurityConfig.java
  backend/src/main/java/ku_rum/backend/global/response/BaseResponse.java
  backend/src/main/java/ku_rum/backend/global/security/jwt/JwtTokenAuthenticationFilter.java
  backend/src/main/java/ku_rum/backend/global/security/jwt/JwtTokenProvider.java
  backend/src/main/java/ku_rum/backend/global/security/jwt/TokenResponse.java
  backend/src/main/resources/application.yml
  backend/src/test/java/ku_rum/backend/config/RestDocsConfiguration.java
  backend/src/test/java/ku_rum/backend/config/RestDocsTestSupport.java
  backend/src/test/java/ku_rum/backend/domain/friend/application/FriendServiceTest.java
  backend/src/test/java/ku_rum/backend/domain/friend/presentation/FriendControllerTest.java
  backend/src/test/java/ku_rum/backend/domain/user/application/MailServiceTest.java
  backend/src/test/java/ku_rum/backend/domain/user/application/UserServiceTest.java
  backend/src/test/java/ku_rum/backend/domain/user/dto/request/EmailValidationRequestTest.java
  backend/src/test/java/ku_rum/backend/domain/user/dto/request/MailSendRequestTest.java
  backend/src/test/java/ku_rum/backend/domain/user/presentation/MailControllerTest.java
  backend/src/test/java/ku_rum/backend/domain/user/presentation/UserControllerTest.java
  backend/src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
Labels: Refactor, BE

#53 refactor: application.yml 파일 삭제
  backend/src/main/resources/application.yml
Labels: environment

#62 [CHORE] 공통 application.yml 파일 추가 및 리드미 파일 업데이트
  README.md
  backend/src/main/resources/application.yml
Labels: environment
