Repository KU-rum/backend, pull requests merged in 2025-03, with the labels that each got.

#132 chore: 젠킨스 CI/CD를 위한 테스트 코드 수정 (#131)
  build.gradle
  src/main/resources/application-test.yml
  src/test/java/ku_rum/backend/domain/auth/application/AuthServiceTest.java
  src/test/java/ku_rum/backend/domain/auth/application/TokenBlacklistServiceTest.java
  src/test/java/ku_rum/backend/domain/auth/presentation/AuthControllerTest.java
  src/test/java/ku_rum/backend/domain/bookmark/application/BookmarkServiceTest.java
  src/test/java/ku_rum/backend/domain/bookmark/presentation/BookmarkControllerTest.java
  src/test/java/ku_rum/backend/domain/building/presentation/BuildingSearchControllerTest.java
  src/test/java/ku_rum/backend/domain/building/service/BuildingCategoryInfoServiceTest.java
  src/test/java/ku_rum/backend/domain/building/service/BuildingInfoServiceTest.java
  src/test/java/ku_rum/backend/domain/chatbot/application/ChatbotServiceTest.java
  src/test/java/ku_rum/backend/domain/chatbot/presentation/ChatbotControllerTest.java
  src/test/java/ku_rum/backend/domain/common/wein/application/WeinServiceTest.java
  src/test/java/ku_rum/backend/domain/friend/application/FriendServiceTest.java
  src/test/java/ku_rum/backend/domain/friend/domain/repository/FriendRepositoryCustomImplTest.java
  src/test/java/ku_rum/backend/domain/friend/presentation/FriendControllerTest.java
  src/test/java/ku_rum/backend/domain/notice/application/NoticeServiceTest.java
  src/test/java/ku_rum/backend/domain/notice/presentation/NoticeControllerTest.java
  src/test/java/ku_rum/backend/domain/recruitment/application/RecruitmentServiceTest.java
  src/test/java/ku_rum/backend/domain/recruitment/domain/RecruitmentTest.java
  src/test/java/ku_rum/backend/domain/recruitment/presentation/RecruitmentControllerTest.java
  src/test/java/ku_rum/backend/domain/reservation/application/ReservationServiceTest.java
  src/test/java/ku_rum/backend/domain/reservation/presentation/ReservationControllerTest.java
  src/test/java/ku_rum/backend/domain/user/application/MailServiceTest.java
  src/test/java/ku_rum/backend/domain/user/application/UserServiceTest.java
  src/test/java/ku_rum/backend/domain/user/domain/repository/UserRepositoryTest.java
  src/test/java/ku_rum/backend/domain/user/presentation/MailControllerTest.java
  src/test/java/ku_rum/backend/domain/user/presentation/UserControllerTest.java
  src/test/java/ku_rum/backend/domain/wein/presentation/WeinControllerTest.java
Labels: chore

#146 chore: 모니터링 서버를 위한 엔드포인트 개방 (#145)
  src/main/java/ku_rum/backend/global/config/security/AuthorizationList.java
Labels: chore

#148 feat: 로깅을 위한 logback 구축 (#147)
  src/main/resources/logback-variables.properties
  src/main/resources/logback.xml
Labels: Feature

#152 docs: Readme 파일 변경 (#151)
  README.md
Labels: documentation

#166 refactor: 유저 아이디 검증 API 수정 (#165)
  src/main/java/ku_rum/backend/domain/common/mail/dto/request/EmailValidationRequest.java
  src/main/java/ku_rum/backend/domain/common/mail/dto/request/LoginIdValidationRequest.java
  src/main/java/ku_rum/backend/domain/user/application/UserService.java
  src/main/java/ku_rum/backend/domain/user/domain/repository/UserRepository.java
  src/main/java/ku_rum/backend/domain/user/presentation/UserController.java
  src/main/java/ku_rum/backend/global/config/security/AuthorizationList.java
  src/main/java/ku_rum/backend/global/exception/handler/UserExceptionControllerAdvice.java
  src/main/java/ku_rum/backend/global/exception/user/DuplicateLoginIdException.java
  src/main/java/ku_rum/backend/global/exception/user/DuplicateNicknameException.java
  src/main/java/ku_rum/backend/global/support/response/status/BaseExceptionResponseStatus.java
  src/test/java/ku_rum/backend/domain/user/application/UserServiceTest.java
  src/test/java/ku_rum/backend/domain/user/dto/request/LoginIdValidationRequestTest.java
  src/test/java/ku_rum/backend/domain/user/presentation/UserControllerTest.java
Labels: Refactor

#168 refactor: 유저 아이디 검증 API 수정 (#167)
  src/main/java/ku_rum/backend/domain/common/mail/dto/request/EmailValidationRequest.java
Labels: Refactor

#178 feat: 커스텀 모니터링 추가 -usercontroller
  build.gradle
  src/main/java/ku_rum/backend/domain/bookmark/dto/request/BookmarkSaveRequest.java
  src/main/java/ku_rum/backend/domain/building/domain/repository/BuildingRepository.java
  src/main/java/ku_rum/backend/domain/building/dto/response/BuildingResponse.java
  src/main/java/ku_rum/backend/domain/category/domain/Category.java
  src/main/java/ku_rum/backend/domain/department/domain/repository/DepartmentRepository.java
  src/main/java/ku_rum/backend/domain/friend/domain/Friend.java
  src/main/java/ku_rum/backend/domain/friend/domain/repository/FriendRepository.java
  src/main/java/ku_rum/backend/domain/friend/dto/request/FriendFindRequest.java
  src/main/java/ku_rum/backend/domain/friend/dto/response/FriendListResponse.java
  src/main/java/ku_rum/backend/domain/friend/presentation/FriendController.java
  src/main/java/ku_rum/backend/domain/recruitment/presentation/RecruitmentController.java
  src/main/java/ku_rum/backend/domain/user/dto/request/ResetAccountRequest.java
  src/main/java/ku_rum/backend/domain/user/dto/response/UserSaveResponse.java
  src/main/java/ku_rum/backend/domain/user/presentation/UserController.java
  src/main/java/ku_rum/backend/global/config/monitoring/CountConfig.java
  src/main/java/ku_rum/backend/global/config/monitoring/TimeConfig.java
  src/main/java/ku_rum/backend/global/dataInit/BuildingInitializer.java
  src/main/resources/application.yml
  src/test/java/ku_rum/backend/config/RestDocsConfiguration.java
  src/test/java/ku_rum/backend/domain/bookmark/presentation/BookmarkControllerTest.java
  src/test/java/ku_rum/backend/domain/building/domain/BuildingCategoryTest.java
  src/test/java/ku_rum/backend/domain/friend/presentation/FriendControllerTest.java
  src/test/java/ku_rum/backend/domain/notice/presentation/NoticeControllerTest.java
Labels: Feature

#182 refactor: 유저 API 리팩토링 (#181)
  .gitignore
  build.gradle
  scripts/merge-and-setup
  scripts/setup_hooks
  src/main/java/ku_rum/backend/domain/auth/application/TokenBlacklistService.java
  src/main/java/ku_rum/backend/domain/building/presentation/BuildingSearchController.java
  src/main/java/ku_rum/backend/domain/category/dto/response/CategoryDetailResponse.java
  src/main/java/ku_rum/backend/domain/common/firebase/application/NotificationService.java
  src/main/java/ku_rum/backend/domain/department/application/DepartmentQueryService.java
  src/main/java/ku_rum/backend/domain/department/application/DepartmentValidator.java
  src/main/java/ku_rum/backend/domain/user/application/UserQueryService.java
  src/main/java/ku_rum/backend/domain/user/application/UserService.java
  src/main/java/ku_rum/backend/domain/user/application/UserValidator.java
  src/main/java/ku_rum/backend/domain/user/domain/AgreementStatus.java
  src/main/java/ku_rum/backend/domain/user/domain/User.java
  src/main/java/ku_rum/backend/domain/user/domain/UserMessage.java
  src/main/java/ku_rum/backend/domain/user/domain/UserRole.java
  src/main/java/ku_rum/backend/domain/user/domain/enums/UserMessage.java
  src/main/java/ku_rum/backend/domain/user/dto/request/NicknameChangeRequest.java
  src/main/java/ku_rum/backend/domain/user/dto/request/ResetAccountRequest.java
  src/main/java/ku_rum/backend/domain/user/dto/request/UserSaveRequest.java
  src/main/java/ku_rum/backend/domain/user/dto/response/LoginIdResponse.java
  src/main/java/ku_rum/backend/domain/user/dto/response/UserSaveResponse.java
  src/main/java/ku_rum/backend/domain/user/presentation/UserController.java
  src/main/java/ku_rum/backend/domain/user/presentation/UserProfileController.java
  src/main/java/ku_rum/backend/global/config/AuthorizationList.java
  src/main/java/ku_rum/backend/global/config/SecurityConfig.java
  src/main/java/ku_rum/backend/global/exception/user/InvalidPasswordException.java
  src/main/java/ku_rum/backend/global/exception/user/NoSuchLoginIdException.java
  src/main/java/ku_rum/backend/global/exception/user/NoSuchUserException.java
  src/main/java/ku_rum/backend/global/handler/UserExceptionControllerAdvice.java
  src/main/java/ku_rum/backend/global/security/JwtTokenAuthenticationFilter.java
  src/main/java/ku_rum/backend/global/security/JwtTokenProvider.java
  src/main/java/ku_rum/backend/global/support/status/BaseExceptionResponseStatus.java
  src/main/java/ku_rum/backend/global/utils/RedisUtils.java
  src/test/java/ku_rum/backend/domain/auth/application/TokenBlacklistServiceTest.java
  src/test/java/ku_rum/backend/domain/bookmark/application/BookmarkServiceTest.java
  src/test/java/ku_rum/backend/domain/bookmark/domain/BookmarkTest.java
  src/test/java/ku_rum/backend/domain/building/presentation/BuildingSearchControllerTest.java
  src/test/java/ku_rum/backend/domain/building/service/BuildingSearchServiceTest.java
  src/test/java/ku_rum/backend/domain/common/firebase/application/NotificationServiceTest.java
  src/test/java/ku_rum/backend/domain/friend/application/FriendServiceTest.java
  src/test/java/ku_rum/backend/domain/friend/domain/FriendTest.java
  src/test/java/ku_rum/backend/domain/notice/domain/NoticeTest.java
  src/test/java/ku_rum/backend/domain/user/application/UserServiceTest.java
  src/test/java/ku_rum/backend/domain/user/domain/UserTest.java
  src/test/java/ku_rum/backend/domain/user/dto/request/UserSaveRequestTest.java
  src/test/java/ku_rum/backend/domain/user/presentation/UserControllerTest.java
  src/test/java/ku_rum/backend/domain/user/presentation/UserProfileControllerTest.java
  src/test/java/ku_rum/backend/global/security/jwt/JwtTokenProviderTest.java
Labels: Refactor

#192 refactor: 메일 서비스 리팩토링 (#191)
  src/main/java/ku_rum/backend/domain/common/mail/application/MailSenderService.java
  src/main/java/ku_rum/backend/domain/common/mail/application/MailService.java
  src/main/java/ku_rum/backend/domain/common/mail/domain/MailAuth.java
  src/main/java/ku_rum/backend/domain/common/mail/domain/MailSendSetting.java
  src/main/java/ku_rum/backend/domain/common/mail/domain/repository/MailAuthRepository.java
  src/main/java/ku_rum/backend/domain/common/mail/dto/request/MailVerificationRequest.java
  src/main/java/ku_rum/backend/domain/common/mail/presentation/MailController.java
  src/main/java/ku_rum/backend/global/support/status/BaseExceptionResponseStatus.java
  src/test/java/ku_rum/backend/domain/common/mail/application/MailServiceTest.java
  src/test/java/ku_rum/backend/domain/common/mail/presentation/MailControllerTest.java
Labels: Refactor

#154 refactor: 크롤링 로직 리팩토링
  build.gradle
  src/main/java/ku_rum/backend/BackendApplication.java
  src/main/java/ku_rum/backend/domain/notice/application/CrawlingService.java
  src/main/java/ku_rum/backend/domain/notice/application/NoticeRedisKey.java
  src/main/java/ku_rum/backend/domain/notice/application/NoticeService.java
  src/main/java/ku_rum/backend/domain/notice/domain/Notice.java
  src/main/java/ku_rum/backend/domain/notice/domain/repository/NoticeRepository.java
  src/main/java/ku_rum/backend/domain/notice/domain/repository/NoticeRepositoryCustom.java
  src/main/java/ku_rum/backend/domain/notice/domain/repository/NoticeRepositoryImpl.java
  src/main/java/ku_rum/backend/domain/notice/presentation/NoticeController.java
  src/main/java/ku_rum/backend/domain/recruitment/domain/Recruitment.java
  src/main/java/ku_rum/backend/global/batch/BatchConfig.java
  src/main/java/ku_rum/backend/global/batch/BatchScheduler.java
  src/main/java/ku_rum/backend/global/batch/CrawlingStep.java
  src/main/java/ku_rum/backend/global/batch/SetRedisKeyStep.java
  src/main/java/ku_rum/backend/global/dataInit/DataLoader.java
  src/main/java/ku_rum/backend/global/exception/notice/InvalidPageException.java
  src/main/java/ku_rum/backend/global/handler/NoticeExceptionControllerAdvice.java
  src/main/java/ku_rum/backend/global/support/status/BaseExceptionResponseStatus.java
  src/main/resources/application-test.yml
  src/test/java/ku_rum/backend/domain/auth/presentation/AuthControllerTest.java
  src/test/java/ku_rum/backend/domain/building/presentation/BuildingSearchControllerTest.java
  src/test/java/ku_rum/backend/domain/building/service/BuildingSearchServiceTest.java
  src/test/java/ku_rum/backend/domain/common/firebase/presentation/NotificationApiControllerTest.java
  src/test/java/ku_rum/backend/domain/common/mail/presentation/MailControllerTest.java
  src/test/java/ku_rum/backend/domain/friend/domain/repository/FriendRepositoryCustomImplTest.java
  src/test/java/ku_rum/backend/domain/notice/application/NoticeServiceTest.java
  src/test/java/ku_rum/backend/domain/recruitment/domain/RecruitmentTest.java
  src/test/java/ku_rum/backend/domain/recruitment/presentation/RecruitmentControllerTest.java
  src/test/java/ku_rum/backend/domain/user/application/UserServiceTest.java
  src/test/java/ku_rum/backend/domain/user/domain/repository/UserRepositoryTest.java
  src/test/java/ku_rum/backend/domain/user/presentation/UserControllerTest.java
  src/test/java/ku_rum/backend/domain/user/presentation/UserProfileControllerTest.java
  src/test/java/ku_rum/backend/global/log/LoggingInterceptorTest.java
Labels: Refactor

#198 refactor: 크롤링 로직 중복 코드 제거
  src/main/java/ku_rum/backend/domain/notice/application/NoticeService.java
  src/main/java/ku_rum/backend/domain/notice/presentation/NoticeController.java
  src/main/java/ku_rum/backend/domain/notice/presentation/NoticeCrawlController.java
Labels: Refactor
