Repository KU-rum/backend, pull requests merged in 2025-02, with the labels that each got.

#49 [BUG] docker container에 chrome driver 설치
  backend/Dockerfile
  backend/build.gradle
  backend/src/main/java/ku_rum/backend/domain/bookmark/domain/Bookmark.java
  backend/src/main/java/ku_rum/backend/domain/notice/domain/Notice.java
  backend/src/main/java/ku_rum/backend/domain/recruitment/domain/Recruitment.java
  backend/src/main/resources/application.yml
Labels: bug

#67 chore: 깃 액션 Jira와 연동 (#66)
  .github/workflows/close-issue-jira.yml
  .github/workflows/create-issue-jira.yml
Labels: environment

#84 [FEATURE] 디스코드 백엔드 채널 남은 PR 알림 구현
  .github/workflows/pr-remaining.yml
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/backend.main.iml
  .idea/recent-my-work.iml
  .idea/vcs.xml
  .idea/workspace.xml
  backend/build.gradle
  backend/src/main/java/ku_rum/backend/domain/building/domain/Building.java
  backend/src/main/java/ku_rum/backend/domain/building/dto/response/BuildingResponse.java
  backend/src/main/java/ku_rum/backend/domain/category/dto/response/CategoryDetailFloorAndMenusProviding.java
  backend/src/main/java/ku_rum/backend/domain/category/dto/response/CategoryDetailResponse.java
  backend/src/main/java/ku_rum/backend/domain/category/dto/response/CategoryKcubeDetailResponse.java
  backend/src/main/java/ku_rum/backend/domain/department/domain/DepartmentType.java
  backend/src/main/java/ku_rum/backend/global/config/dataInsert/DataLoader.java
  backend/src/main/java/ku_rum/backend/global/dataInsert/BuildingCategoryInitializer.java
  backend/src/main/java/ku_rum/backend/global/dataInsert/BuildingInitializer.java
  backend/src/main/java/ku_rum/backend/global/dataInsert/CategoryInitializer.java
  backend/src/main/java/ku_rum/backend/global/dataInsert/DataLoader.java
  backend/src/main/java/ku_rum/backend/global/dataInsert/DepartmentInitializer.java
  backend/src/main/java/ku_rum/backend/global/dataInsert/MenuInitializer.java
  backend/src/main/java/ku_rum/backend/global/exception/building/BuildingCategoryNotProvidingException.java
  backend/src/main/resources/application.yml
  backend/src/test/java/ku_rum/backend/domain/building/presentation/BuildingSearchControllerTest.java
  remainingPR.py
  requirements.txt
Labels: Feature, D-2

#91 chore: 깃 허브 액션을 이용한 CI/CD 구축 (#77)
  .github/workflows/cd-backend.yml
  .github/workflows/ci-backend.yml
Labels: chore, D-0

#94 [REFACTOR] 일부 메소드 수정 및 테스트 코드 적용
  .idea/workspace.xml
  backend/src/docs/asciidoc/building.adoc
  backend/src/main/java/ku_rum/backend/BackendApplication.java
  backend/src/main/java/ku_rum/backend/domain/building/application/BuildingSearchService.java
  backend/src/main/java/ku_rum/backend/domain/building/presentation/BuildingSearchController.java
  backend/src/main/java/ku_rum/backend/domain/buildingCategory/domain/BuildingCategory.java
  backend/src/main/java/ku_rum/backend/domain/buildingCategory/domain/repository/BuildingCategoryQueryRepository.java
  backend/src/main/java/ku_rum/backend/domain/buildingCategory/domain/repository/BuildingCategoryRepository.java
  backend/src/main/java/ku_rum/backend/domain/buildingCategory/dto/request/BuildindgCategoryRequest.java
  backend/src/main/java/ku_rum/backend/domain/category/application/CategoryService.java
  backend/src/main/java/ku_rum/backend/domain/category/domain/CategoryDetail.java
  backend/src/main/java/ku_rum/backend/domain/category/domain/repository/CategoryRepository.java
  backend/src/main/java/ku_rum/backend/domain/category/dto/response/CategoryDetailFloorAndMenusProviding.java
  backend/src/main/java/ku_rum/backend/domain/category/dto/response/CategoryDetailResponse.java
  backend/src/main/java/ku_rum/backend/domain/category/dto/response/CategoryKcubeDetailResponse.java
  backend/src/main/java/ku_rum/backend/domain/menu/domain/repository/MenuQueryRepository.java
  backend/src/main/java/ku_rum/backend/domain/menu/domain/repository/MenuRepository.java
  backend/src/main/java/ku_rum/backend/domain/menu/response/MenuSimpleResponse.java
  backend/src/main/java/ku_rum/backend/domain/notice/domain/Notice.java
  backend/src/main/java/ku_rum/backend/domain/user/application/UserService.java
  backend/src/main/java/ku_rum/backend/domain/user/dto/request/UserSaveRequest.java
  backend/src/main/java/ku_rum/backend/global/config/redis/RedisUtil.java
  backend/src/main/java/ku_rum/backend/global/config/security/SecurityConfig.java
  backend/src/main/java/ku_rum/backend/global/dataInsert/BuildingCategoryInitializer.java
  backend/src/main/java/ku_rum/backend/global/dataInsert/DataLoader.java
  backend/src/main/java/ku_rum/backend/global/dataInsert/MenuInitializer.java
  backend/src/main/java/ku_rum/backend/global/security/jwt/JwtProperties.java
  backend/src/main/resources/static/docs/building.html
  backend/src/main/resources/static/docs/user.html
  backend/src/test/java/ku_rum/backend/domain/building/domain/BuildingCategoryTest.java
  backend/src/test/java/ku_rum/backend/domain/building/presentation/BuildingSearchControllerTest.java
  backend/src/test/java/ku_rum/backend/domain/building/service/BuildingCategoryInfoServiceTest.java
  backend/src/test/java/ku_rum/backend/domain/building/service/BuildingInfoServiceTest.java
  backend/src/test/java/ku_rum/backend/domain/user/presentation/MailControllerTest.java
Labels: Refactor, D-0

#46 [FEATURE] Oauth 적용
  backend/build.gradle
  backend/src/main/java/ku_rum/backend/domain/oauth/application/CustomOAuth2UserService.java
  backend/src/main/java/ku_rum/backend/domain/oauth/application/DefaultOAuth2UserServiceNaver.java
  backend/src/main/java/ku_rum/backend/domain/oauth/domain/DefaultOAuth2UserNaver.java
  backend/src/main/java/ku_rum/backend/domain/oauth/domain/OAuthAttributes.java
  backend/src/main/java/ku_rum/backend/domain/oauth/domain/UserProfile.java
  backend/src/main/java/ku_rum/backend/domain/oauth/util/TokenValidator.java
  backend/src/main/java/ku_rum/backend/domain/user/domain/User.java
  backend/src/main/java/ku_rum/backend/global/config/security/SecurityConfig.java
  backend/src/main/java/ku_rum/backend/global/security/jwt/CustomUserDetails.java
  backend/src/main/java/ku_rum/backend/global/security/jwt/JwtTokenAuthenticationFilter.java
  backend/src/main/java/ku_rum/backend/global/security/jwt/JwtTokenProvider.java
  backend/src/main/resources/static/index.html
Labels: Feature, BE, D-0

#105 feat: USER, 스프링 시큐리티 리팩토링
  backend/src/main/java/ku_rum/backend/global/dataInsert/BuildingCategoryInitializer.java
  backend/src/main/java/ku_rum/backend/global/dataInsert/BuildingInitializer.java
  backend/src/main/java/ku_rum/backend/global/dataInsert/CategoryInitializer.java
  backend/src/main/java/ku_rum/backend/global/dataInsert/DataLoader.java
  backend/src/main/java/ku_rum/backend/global/dataInsert/DepartmentInitializer.java
  backend/src/main/java/ku_rum/backend/global/dataInsert/MenuInitializer.java
  src/main/java/ku_rum/backend/domain/auth/application/AuthService.java
  src/main/java/ku_rum/backend/domain/auth/presentation/AuthController.java
  src/main/java/ku_rum/backend/domain/bookmark/presentation/BookmarkController.java
  src/main/java/ku_rum/backend/domain/department/domain/repository/DepartmentRepository.java
  src/main/java/ku_rum/backend/domain/friend/application/FriendService.java
  src/main/java/ku_rum/backend/domain/friend/domain/Friend.java
  src/main/java/ku_rum/backend/domain/friend/domain/FriendMessage.java
  src/main/java/ku_rum/backend/domain/friend/domain/FriendStatus.java
  src/main/java/ku_rum/backend/domain/friend/domain/repository/FriendRepository.java
  src/main/java/ku_rum/backend/domain/friend/domain/repository/FriendRepositoryCustom.java
  src/main/java/ku_rum/backend/domain/friend/domain/repository/FriendRepositoryCustomImpl.java
  src/main/java/ku_rum/backend/domain/friend/dto/request/FriendFindRequest.java
  src/main/java/ku_rum/backend/domain/friend/dto/response/FriendListResponse.java
  src/main/java/ku_rum/backend/domain/friend/presentation/FriendController.java
  src/main/java/ku_rum/backend/domain/mail/application/MailService.java
  src/main/java/ku_rum/backend/domain/mail/presentation/MailController.java
  src/main/java/ku_rum/backend/domain/oauth/application/CustomOAuth2UserService.java
  src/main/java/ku_rum/backend/domain/user/application/UserService.java
  src/main/java/ku_rum/backend/domain/user/domain/User.java
  src/main/java/ku_rum/backend/domain/user/domain/UserMessage.java
  src/main/java/ku_rum/backend/domain/user/domain/UserRole.java
  src/main/java/ku_rum/backend/domain/user/domain/repository/UserRepository.java
  src/main/java/ku_rum/backend/domain/user/dto/request/ProfileChangeRequest.java
  src/main/java/ku_rum/backend/domain/user/dto/request/ResetAccountRequest.java
  src/main/java/ku_rum/backend/domain/user/dto/request/UserSaveRequest.java
  src/main/java/ku_rum/backend/domain/user/dto/response/UserSaveResponse.java
  src/main/java/ku_rum/backend/domain/user/presentation/UserController.java
  src/main/java/ku_rum/backend/domain/wein/application/WeinService.java
  src/main/java/ku_rum/backend/domain/wein/presentation/WeinController.java
  src/main/java/ku_rum/backend/global/config/security/AuthorizationList.java
  src/main/java/ku_rum/backend/global/config/security/SecurityConfig.java
  src/main/java/ku_rum/backend/global/dataInit/BuildingCategoryInitializer.java
  src/main/java/ku_rum/backend/global/dataInit/BuildingInitializer.java
  src/main/java/ku_rum/backend/global/dataInit/CategoryInitializer.java
  src/main/java/ku_rum/backend/global/dataInit/DataLoader.java
  src/main/java/ku_rum/backend/global/dataInit/DepartmentInitializer.java
  src/main/java/ku_rum/backend/global/dataInit/MenuInitializer.java
  src/main/java/ku_rum/backend/global/handler/AuthExceptionControllerAdvice.java
  src/main/java/ku_rum/backend/global/response/status/BaseExceptionResponseStatus.java
  src/main/java/ku_rum/backend/global/security/jwt/CustomUserDetails.java
  src/main/java/ku_rum/backend/global/security/jwt/JwtTokenProvider.java
  src/main/java/ku_rum/backend/global/security/jwt/UserUtils.java
  src/main/java/ku_rum/backend/global/security/jwt/dto/TokenResponse.java
  src/test/java/ku_rum/backend/domain/friend/application/FriendServiceTest.java
  src/test/java/ku_rum/backend/domain/friend/presentation/FriendControllerTest.java
  src/test/java/ku_rum/backend/domain/user/application/UserServiceTest.java
  src/test/java/ku_rum/backend/domain/user/presentation/UserControllerTest.java
Labels: Feature

#111 feature: AOP를 이용한 API 로깅 처리 (#60)
  build.gradle
  docker-compose.yml
  src/docs/asciidoc/building.adoc
  src/docs/asciidoc/user.adoc
  src/main/java/ku_rum/backend/domain/bookmark/application/BookmarkService.java
  src/main/java/ku_rum/backend/domain/bookmark/dto/request/BookmarkSaveRequest.java
  src/main/java/ku_rum/backend/domain/bookmark/presentation/BookmarkController.java
  src/main/java/ku_rum/backend/domain/building/application/BuildingSearchService.java
  src/main/java/ku_rum/backend/domain/category/application/CategoryService.java
  src/main/java/ku_rum/backend/domain/friend/application/FriendService.java
  src/main/java/ku_rum/backend/domain/recruitment/presentation/RecruitmentController.java
  src/main/java/ku_rum/backend/domain/reservation/dto/response/WeinLoginResponse.java
  src/main/java/ku_rum/backend/domain/wein/application/WeinService.java
  src/main/java/ku_rum/backend/domain/wein/dto/request/WeinLoginRequest.java
  src/main/java/ku_rum/backend/domain/wein/presentation/WeinController.java
  src/main/java/ku_rum/backend/global/config/WebConfig.java
  src/main/java/ku_rum/backend/global/config/security/AuthorizationList.java
  src/main/java/ku_rum/backend/global/config/security/SecurityConfig.java
  src/main/java/ku_rum/backend/global/exception/category/CategoryNotExistException.java
  src/main/java/ku_rum/backend/global/exception/category/CategoryNotProvidingDetailException.java
  src/main/java/ku_rum/backend/global/exception/notice/DuplicateNoticeException.java
  src/main/java/ku_rum/backend/global/exception/wein/WeinException.java
  src/main/java/ku_rum/backend/global/handler/CategoryExceptionControllerAdvice.java
  src/main/java/ku_rum/backend/global/handler/WeinExceptionControllerAdvice.java
  src/main/java/ku_rum/backend/global/log/LoggingInterceptor.java
  src/main/java/ku_rum/backend/global/log/RequestBodyWrappingFIlter.java
  src/main/java/ku_rum/backend/global/log/domain/ApiLog.java
  src/main/java/ku_rum/backend/global/log/domain/repository/ApiLogRepository.java
  src/main/java/ku_rum/backend/global/response/status/BaseExceptionResponseStatus.java
  src/main/java/ku_rum/backend/global/security/jwt/CustomUserDetails.java
  src/main/java/ku_rum/backend/global/security/jwt/UserUtils.java
  src/test/java/ku_rum/backend/config/RestDocsConfiguration.java
  src/test/java/ku_rum/backend/config/RestDocsTestSupport.java
  src/test/java/ku_rum/backend/domain/auth/presentation/AuthControllerTest.java
  src/test/java/ku_rum/backend/domain/bookmark/application/BookmarkServiceTest.java
  src/test/java/ku_rum/backend/domain/bookmark/presentation/BookmarkControllerTest.java
  src/test/java/ku_rum/backend/domain/building/presentation/BuildingSearchControllerTest.java
  src/test/java/ku_rum/backend/domain/building/service/BuildingCategoryInfoServiceTest.java
  src/test/java/ku_rum/backend/domain/friend/application/FriendServiceTest.java
  src/test/java/ku_rum/backend/domain/friend/domain/FriendTest.java
  src/test/java/ku_rum/backend/domain/friend/presentation/FriendControllerTest.java
  src/test/java/ku_rum/backend/domain/notice/presentation/NoticeControllerTest.java
  src/test/java/ku_rum/backend/domain/recruitment/presentation/RecruitmentControllerTest.java
  src/test/java/ku_rum/backend/domain/reservation/presentation/ReservationControllerTest.java
  src/test/java/ku_rum/backend/domain/user/dto/request/UserSaveRequestTest.java
  src/test/java/ku_rum/backend/domain/user/presentation/MailControllerTest.java
  src/test/java/ku_rum/backend/domain/user/presentation/UserControllerTest.java
  src/test/java/ku_rum/backend/domain/wein/presentation/WeinControllerTest.java
Labels: D-0

#126 refactor: Jacoco 커버리지를 위한 테스트 코드 추가 (#123)
  build.gradle
  src/main/java/ku_rum/backend/domain/chatbot/application/ChatbotService.java
  src/test/java/ku_rum/backend/domain/chatbot/application/ChatbotServiceTest.java
Labels: Refactor

#128 chore: 젠킨스를 이용한 무중단 배포 적용 (#127)
  .gitignore
  Dockerfile
  Jenkinsfile
  build.gradle
  docker/Dockerfile
  docker/docker-compose.blue.yml
  docker/docker-compose.green.yml
  docker/docker-compose.yml
  scripts/deploy.sh
  src/main/resources/application.yml
  src/test/java/ku_rum/backend/domain/common/wein/application/WeinServiceTest.java
Labels: chore
