Repository KU-rum/backend, pull requests merged in 2025-05, with the labels that each got.

#209 feat: 소셜 로그인 (구글/네이버/카카오) 적용
  src/main/java/ku_rum/backend/domain/auth/application/AuthService.java
  src/main/java/ku_rum/backend/domain/auth/presentation/AuthController.java
  src/main/java/ku_rum/backend/domain/common/oauth/application/CustomOAuth2UserService.java
  src/main/java/ku_rum/backend/domain/common/oauth/application/DefaultOAuth2UserServiceNaver.java
  src/main/java/ku_rum/backend/domain/common/oauth/domain/DefaultOAuth2UserNaver.java
  src/main/java/ku_rum/backend/domain/common/oauth/domain/OAuthAttributes.java
  src/main/java/ku_rum/backend/domain/common/oauth/domain/UserProfile.java
  src/main/java/ku_rum/backend/domain/common/oauth/util/TokenValidator.java
  src/main/java/ku_rum/backend/domain/oauth/application/CustomOAuth2UserService.java
  src/main/java/ku_rum/backend/domain/oauth/domain/GoogleOAuth2MemberInfo.java
  src/main/java/ku_rum/backend/domain/oauth/domain/KakaoOAuth2MemberInfo.java
  src/main/java/ku_rum/backend/domain/oauth/domain/NaverOAuth2MemberInfo.java
  src/main/java/ku_rum/backend/domain/oauth/domain/OAuth2MemberInfo.java
  src/main/java/ku_rum/backend/domain/oauth/domain/ProviderType.java
  src/main/java/ku_rum/backend/domain/oauth/handler/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/ku_rum/backend/domain/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/ku_rum/backend/domain/oauth/handler/OAuth2MemberInfoFactory.java
  src/main/java/ku_rum/backend/domain/oauth/handler/TempTokenProvider.java
  src/main/java/ku_rum/backend/domain/oauth/util/AppProperties.java
  src/main/java/ku_rum/backend/domain/oauth/util/CookieUtils.java
  src/main/java/ku_rum/backend/domain/user/domain/User.java
  src/main/java/ku_rum/backend/domain/user/domain/repository/UserRepository.java
  src/main/java/ku_rum/backend/global/config/AuthorizationList.java
  src/main/java/ku_rum/backend/global/config/SecurityConfig.java
  src/main/java/ku_rum/backend/global/exception/oauth/OAuthAuthorizeException.java
  src/main/java/ku_rum/backend/global/exception/oauth/OAuthProviderMissMatchException.java
  src/main/java/ku_rum/backend/global/handler/AuthExceptionControllerAdvice.java
  src/main/java/ku_rum/backend/global/security/CustomUserDetails.java
  src/main/java/ku_rum/backend/global/support/status/BaseExceptionResponseStatus.java
  src/main/java/ku_rum/backend/global/utill/RedisUtil.java
  src/main/resources/application-test.yml
  src/test/java/ku_rum/backend/domain/auth/presentation/AuthControllerTest.java
  src/test/java/ku_rum/backend/domain/bookmark/application/BookmarkServiceTest.java
  src/test/java/ku_rum/backend/domain/bookmark/domain/BookmarkTest.java
  src/test/java/ku_rum/backend/domain/common/firebase/presentation/NotificationApiControllerTest.java
  src/test/java/ku_rum/backend/domain/common/mail/presentation/MailControllerTest.java
  src/test/java/ku_rum/backend/domain/friend/application/FriendServiceTest.java
  src/test/java/ku_rum/backend/domain/friend/domain/FriendTest.java
  src/test/java/ku_rum/backend/domain/notice/domain/NoticeRecentControllerTest.java
  src/test/java/ku_rum/backend/domain/notice/domain/NoticeTest.java
  src/test/java/ku_rum/backend/domain/notice/domain/NoticeViewControllerTest.java
  src/test/java/ku_rum/backend/domain/recruitment/presentation/RecruitmentControllerTest.java
  src/test/java/ku_rum/backend/domain/user/application/UserServiceTest.java
  src/test/java/ku_rum/backend/domain/user/domain/UserTest.java
  src/test/java/ku_rum/backend/domain/user/domain/repository/UserRepositoryTest.java
  src/test/java/ku_rum/backend/domain/user/presentation/UserControllerTest.java
  src/test/java/ku_rum/backend/domain/user/presentation/UserProfileControllerTest.java
Labels: Feature

#219 refactor: UserResponse에 학과 추가 (#218)
  src/main/java/ku_rum/backend/domain/auth/application/AuthService.java
  src/main/java/ku_rum/backend/domain/department/domain/repository/UserDepartmentRepository.java
  src/main/java/ku_rum/backend/domain/department/dto/DepartmentResponse.java
  src/main/java/ku_rum/backend/domain/user/dto/response/UserResponse.java
  src/test/java/ku_rum/backend/domain/auth/presentation/AuthControllerTest.java
Labels: Refactor

#223 feat: 친구 삭제/추가 API 구현 (#221)
  src/main/java/ku_rum/backend/domain/friend/application/FriendManageService.java
  src/main/java/ku_rum/backend/domain/friend/application/FriendQueryService.java
  src/main/java/ku_rum/backend/domain/friend/application/FriendService.java
  src/main/java/ku_rum/backend/domain/friend/domain/FriendBlock.java
  src/main/java/ku_rum/backend/domain/friend/domain/FriendReport.java
  src/main/java/ku_rum/backend/domain/friend/domain/repository/FriendBlockRepository.java
  src/main/java/ku_rum/backend/domain/friend/domain/repository/FriendReportRepository.java
  src/main/java/ku_rum/backend/domain/friend/domain/repository/FriendRepository.java
  src/main/java/ku_rum/backend/domain/friend/dto/request/FriendBlockRequest.java
  src/main/java/ku_rum/backend/domain/friend/dto/request/FriendReportRequest.java
  src/main/java/ku_rum/backend/domain/friend/presentation/FriendController.java
  src/main/java/ku_rum/backend/domain/user/application/UserQueryService.java
  src/main/java/ku_rum/backend/domain/user/application/UserService.java
  src/main/java/ku_rum/backend/domain/user/application/UserValidator.java
  src/main/java/ku_rum/backend/global/exception/global/GlobalException.java
  src/main/java/ku_rum/backend/global/handler/GlobalExceptionControllerAdvice.java
  src/main/java/ku_rum/backend/global/support/status/BaseExceptionResponseStatus.java
  src/main/java/ku_rum/backend/global/support/status/ResponseStatus.java
  src/main/java/ku_rum/backend/global/utill/UserUtil.java
  src/test/java/ku_rum/backend/domain/friend/application/FriendServiceTest.java
  src/test/java/ku_rum/backend/domain/notice/domain/NoticeRecentControllerTest.java
  src/test/java/ku_rum/backend/domain/user/domain/repository/UserRepositoryTest.java
  src/test/java/ku_rum/backend/domain/user/presentation/UserControllerTest.java
Labels: Refactor

#232 chore: 젠킨스 빌드 밀림 현상 확인용 (#225)
  docker/docker-compose.blue.yml
Labels: chore

#235 feat: 장소 디테일 정보(부제목,설명) 추가 api 구현
  src/main/java/ku_rum/backend/domain/category/presentation/CategoryViewController.java
  src/main/java/ku_rum/backend/domain/place/application/PlaceViewService.java
  src/main/java/ku_rum/backend/domain/place/domain/Place.java
  src/main/java/ku_rum/backend/domain/place/dto/response/PlaceDetailView.java
  src/main/java/ku_rum/backend/domain/place/presentation/PlaceViewController.java
  src/main/java/ku_rum/backend/global/dataInit/DataLoader.java
  src/main/java/ku_rum/backend/global/dataInit/PlaceInitializer.java
  src/main/java/ku_rum/backend/global/exception/place/PlaceNotFoundException.java
  src/main/java/ku_rum/backend/global/handler/PlaceExceptionControllerAdvice.java
  src/main/java/ku_rum/backend/global/support/status/BaseExceptionResponseStatus.java
  src/test/java/ku_rum/backend/domain/place/presentation/PlaceViewControllerTest.java
Labels: Feature

#241 chore: NoitceServiceTest삭제 (#240)
  Jenkinsfile
  src/main/java/ku_rum/backend/domain/alim/domain/Alim.java
  src/main/java/ku_rum/backend/domain/building/domain/Building.java
  src/main/java/ku_rum/backend/domain/place/presentation/PlaceViewController.java
  src/main/java/ku_rum/backend/global/config/S3Config.java
  src/test/java/ku_rum/backend/domain/notice/application/NoticeServiceTest.java
Labels: chore

#243 chore: Jenkinsfile 수정
  Jenkinsfile
Labels: chore

#249 feat: 친구 삭제/닉네임 부분 검색 추가
  src/main/java/ku_rum/backend/domain/friend/application/FriendManageService.java
  src/main/java/ku_rum/backend/domain/friend/application/FriendQueryService.java
  src/main/java/ku_rum/backend/domain/friend/domain/repository/FriendRepository.java
  src/main/java/ku_rum/backend/domain/friend/dto/response/FriendSearchResponse.java
  src/main/java/ku_rum/backend/domain/friend/presentation/FriendManageController.java
  src/main/java/ku_rum/backend/domain/friend/presentation/FriendQueryController.java
  src/main/java/ku_rum/backend/domain/user/domain/repository/UserRepository.java
  src/main/java/ku_rum/backend/global/support/status/BaseExceptionResponseStatus.java
  src/test/java/ku_rum/backend/domain/friend/presentation/FriendManageControllerTest.java
  src/test/java/ku_rum/backend/domain/friend/presentation/FriendQueryControllerTest.java
Labels: Feature
